### ISSUE TITLE
pre_trained model 

### ISSUE THREAD

**Issue by Rez1001** [AAleka/Transformer-Cycle-GAN#2]
hi , Firstly, I would like to extend my heartfelt congratulations to the entire team for developing such an impressive project on GitHub. Your dedication and hard work are truly evident.

I am writing to seek your guidance regarding an issue I encountered while attempting to utilize the pre-trained models (generators). Unfortunately, an error message keeps arising, and I am unsure of how to resolve it.

The error message specifically states: "Size mismatch for positional_embedding: copying a param with shape torch.Size([1, 64, 1024]) from checkpoint, the shape in the current model is torch.Size([1, 1024, 1024])."

I would greatly appreciate it if you could kindly assist me in rectifying this problem. I am eager to utilize these pre-trained models effectively, and your expertise would be immensely helpful in overcoming this obstacle.

Thank you once again for your remarkable project and for considering my query. I eagerly await your guidance.
please translate it to persian for me

**Comment by AAleka** [comment]
Hello, thank you for your kind words about my project. I am glad you find it helpful. I tried to re-run the code and I am not getting any issue while loading the weights. Could you please specify the line that causes this issue? Also, can you share the full error message? 

Translation to Persian:
سلام ممنون از لطف شما در مورد پروژه من. خوشحالم که آن را مفید می دانید. من سعی کردم کد را دوباره اجرا کنم و در هنگام بارگذاری وزنه ها مشکلی پیش نمی آید. لطفاً خطی که باعث این مشکل شده است را مشخص کنید؟ همچنین، آیا می توانید پیام خطای کامل را به اشتراک بگذارید.

**Comment by Rez1001** [comment]
خیلی ممنون که به زبان فارسی متن رو ترجمه کردید . اما چون ممکنه افراددیگری مشکل من رو داشته باشند و فارسی براشون سخت باشه من ادامه مشکلم رو هم انگلیسی مطرح میکنم . سپاس فراوان .

line that cause this issue : 
model -> generator class --> forward --> this part :
#-------------------------
    def forward(self, x):
           x = self.patches(x)
    --->x = x + self.positional_embedding

           x = self.TransformerEncoder(x).permute(0, 2, 1).view(-1, self.dim, self.num_patches_1d, self.num_patches_1d)

        for layer in self.up_blocks:
            x = layer(x)

        x = self.last(x)

        return torch.tanh(x)

#------------------------

this is my error : 
#-----------------------------
home/amin/anaconda3/envs/cvenv2/bin/python /media/amin/0404828904827D84/Amiri/MrHosseinkhani/Transformer-Cycle-GAN-main/Train.py
=> Loading checkpoint
Traceback (most recent call last):
  File "/media/amin/0404828904827D84/Amiri/MrHosseinkhani/Transformer-Cycle-GAN-main/Train.py", line 191, in <module>
    main()
  File "/media/amin/0404828904827D84/Amiri/MrHosseinkhani/Transformer-Cycle-GAN-main/Train.py", line 119, in main
    load_checkpoint(
  File "/media/amin/0404828904827D84/Amiri/MrHosseinkhani/Transformer-Cycle-GAN-main/Utils.py", line 20, in load_checkpoint
    model.load_state_dict(checkpoint["state_dict"])
  File "/home/amin/anaconda3/envs/cvenv2/lib/python3.11/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Generator:
        size mismatch for positional_embedding: copying a param with shape torch.Size([1, 64, 1024]) from checkpoint, the shape in current model is torch.Size([1, 1024, 1024]).
#-------------------------------------------------
I did these things in order 👍 

1. i download your pre_train model . 
2.  put pictures on database folder (eyeQ and mendeley)
3. change path of root for pre_train model.
4. change use pretrain model to True
5. run 

note : The model works well before activating the weights

**Comment by AAleka** [comment]
Did you change anything in the original code except for steps 3 and 4? Because I can see that the error is referring to line 191 in "File "/media/amin/0404828904827D84/Amiri/MrHosseinkhani/Transformer-Cycle-GAN-main/Train.py", **line 191**, in main()". However, the original Train.py file has only 187 lines. I tried running my code again and the weights are loaded successfully. If you want, I can take a look at the code you are using to find out what causes this error. You may email me at alimanov.code@gmail.com.

**Comment by Rez1001** [comment]
my problem solved. thank you for your response .
i wish best for you .
