### ISSUE TITLE
how to test/train the net with rectangular images

### ISSUE THREAD

**Issue by GH-lhc** [AAleka/Transformer-Cycle-GAN#3]
Hi
It is very interting work! thank you for providing the code. I want to know how to test/train the net with rectangular images(for example, 512*256). Can you give me some advice?
Thanks.

**Comment by AAleka** [comment]
Hi. I just edited the Generator model in Model.py, now you need to add parameters (weight=512, height=256) in the model initialization.

**Comment by GH-lhc** [comment]
@AAleka Thank you very much, i will try it later.

**Comment by GH-lhc** [comment]
@AAleka Hi. Thank your respose! I have two other questiones. The test results was still 256*256 when my test image is 512*256. It is maybe because the code "A.Resize(width=256, height=256),"on line 81 of the Test.py. Is that so? and i want to known can I train the network with the size 512*256 of both input and ouput images?

**Comment by AAleka** [comment]
Hi. Yes, you should set the height and width for your particuler case in the Test.py. But you also need to train the network for this case, so in the Train.py you should set your image size in A.Resize(width=..., height=...) and in the model initialization. For example, model = Generator(width=..., heigth=...).

**Comment by GH-lhc** [comment]
@AAleka thank you very much. But i meet the bug again. I have set my image size in A.Resize(width=512, height=256), gen = Generator(width=512, height=256).to(DEVICE).  when i run Train.py.  The error is as fllows:Traceback (most recent call last):
  File "F:\LHC\algrithm_2023_11\Transformer-Cycle-GAN-main\Train.py", line 187, in <module>
    main()
  File "F:\LHC\algrithm_2023_11\Transformer-Cycle-GAN-main\Train.py", line 144, in main
    train_fn(disc_A, disc_B, gen_A, gen_B, loader, opt_disc, opt_gen, L1, mse, d_scaler, g_scaler, epoch)
  File "F:\LHC\algrithm_2023_11\Transformer-Cycle-GAN-main\Train.py", line 30, in train_fn
    fake_a = gen_A(b)
  File "D:\Anaconda3\envs\srcgan\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "F:\LHC\algrithm_2023_11\Transformer-Cycle-GAN-main\Model.py", line 148, in forward
    x = x + self.positional_embedding
RuntimeError: The size of tensor a (2048) must match the size of tensor b (1024) at non-singleton dimension 1
Any advice will help me. Thank you!

**Comment by AAleka** [comment]
Thanks for letting me know! I fixed this bug in the last commit, modified files are: Train.py, Model.py, Test.py. Also I made it easier to specify the image dimensions, so look for IMAGE_WIDTH and IMAGE_HEIGHT in the Train.py and Test.py. Modifying these variables is enough.
